version: '3'

services:

#  fs-api:
#    image: tianon/true
#    volumes:
#      - ./nginx-conf:/etc/nginx/conf.d
#      - ./nginx-certs:/etc/nginx/ssl
#      - ./nginx-logs:/etc/nginx/logs

# MySQL database for Keycloak
  db:
    image: mysql:5.7
    env_file: ./env/.envmysql
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_accounts:/var/lib/mysql
   
# Keycloak server
  sso:
    image: dina/keycloak:v0.1
    env_file: 
      - ./env/.envmysql
      - ./env/.envaccounts
    environment:
      - TZ=Europe/Stockholm
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - PROXY_ADDRESS_FORWARDING=true 
    links:
      - db:mysql

# Java JSON-API
  api:
    image: dina/accounts-api:v0.1
    env_file:  
      - ./env/.envaccounts
    environment:
      - VIRTUAL_HOST=beta-api.dina-web.net
    volumes:
      - ./env/.envapi:/usr/src/myapp/project-initdata.yml
    ports:
      - "8181:8181"

# Keycloak API proxy
  ws:
    image: nginx
    container_name: beta-sso.dina-web.net
    environment:
      - VIRTUAL_HOST=beta-sso.dina-web.net
  #  links:
  #    - api 
    volumes:
      - ./nginx-conf/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx-certs:/etc/nginx/ssl
    depends_on:
      - sso

# Ember frontend
  ui:
    image: dina/accounts-ui:v0.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.template
    environment:
      - VIRTUAL_HOST=beta-accounts.dina-web.net
      - VIRTUAL_PROTO=http
      - NGINX_HOST=beta-accounts.dina-web.net
      - NGINX_PORT=80
    command: /bin/ash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_ROOT $$NGINX_INDEX' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

# Generic proxy
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

volumes:
  db_accounts: 
