version: '3.1'

services:

  db:
    image: mysql:5.7
    env_file: ./env/.envmysql
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_accounts:/var/lib/mysql
   
  sso:
    image: dina/keycloak:v0.1
    env_file: 
      - ./env/.envmysql
      - ./env/.envaccounts
    environment:
      - TZ=Europe/Stockholm
      - MYSQL_PORT_3306_TCP_ADDR=mysql
      - MYSQL_PORT_3306_TCP_PORT=3306
      - PROXY_ADDRESS_FORWARDING=true
    links:
      - db:mysql

  api:
    image: dina/accounts-api:v0.1
    environment:
      - VIRTUAL_HOST=${ACCOUNTS_FQDN_API}
    volumes:
      - ./env/.envapi:/usr/src/myapp/project-initdata.yml

  ws:
    image: nginx
    container_name: ${ACCOUNTS_FQDN_SSO}
    environment:
      - VIRTUAL_HOST=${ACCOUNTS_FQDN_SSO}
    volumes:
      - ./nginx-conf/app.conf:/etc/nginx/conf.d/app.conf.template
      - ./nginx-certs:/etc/nginx/ssl
    command: /bin/ash -c "envsubst '$$VIRTUAL_HOST' < /etc/nginx/conf.d/app.conf.template > /etc/nginx/conf.d/app.conf && nginx -g 'daemon off;'"
    depends_on:
      - sso

  ui:
    image: dina/accounts-ui:v0.1
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.template
    environment:
      - VIRTUAL_HOST=${ACCOUNTS_FQDN_UI}
      - VIRTUAL_PROTO=http
      - NGINX_HOST=${ACCOUNTS_FQDN_UI}
      - NGINX_PORT=80
    command: /bin/ash -c "envsubst '$$NGINX_HOST $$NGINX_PORT $$NGINX_ROOT $$NGINX_INDEX' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./certs:/etc/nginx/certs

  dnsmasq:
# https://stackoverflow.com/questions/35693117/how-can-i-give-docker-containers-access-to-a-dnsmasq-local-dns-resolver-on-the-h
# https://github.com/mskyttner/dns-test-docker
    image: andyshinn/dnsmasq:2.76
    command: --server=8.8.8.8 --server=193.10.57.11 --log-facility=-
    cap_add: 
      - NET_ADMIN 
    ports:
      - 172.17.0.1:53:53/tcp
      - 172.17.0.1:53:53/udp

volumes:
  db_accounts: 
